In [5]:
#Load the data
import pandas as pd
data = pd.read_csv('dataset_Seminar1.txt', sep=' ', header=None)
display(data.head())

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,40.0,60000000.0,22.0,39.0,858.0,63.0,80.0,4000.0,-42.928330,-63.163012,-74.965338,0.415189,7.208644e+06,1.229466e+07,1.084041,0.875490
1,35.0,52500000.0,20.0,33.0,660.0,31.0,40.0,10000.0,-47.815800,-63.298410,-72.847989,0.485311,1.545116e+07,1.275042e+07,1.111263,0.873785
2,16.0,12000000.0,34.0,14.0,476.0,255.0,40.0,4000.0,-46.138494,-60.076333,-70.044800,0.099413,6.743660e+06,2.251690e+06,0.880036,0.849701
3,37.0,18500000.0,35.0,7.0,245.0,31.0,80.0,10000.0,-42.708813,-60.141393,-72.029643,0.493704,1.675025e+07,1.211374e+07,1.126341,0.860103
4,18.0,4500000.0,36.0,35.0,1260.0,127.0,160.0,8000.0,-45.492991,-63.780783,-76.225550,0.011664,4.500000e+06,1.446000e-03,0.276770,0.275687

In [6]:
#Añadimos labels a la data porque me vuelvo loco. (Perdón por comentarios en varios idiomas voy a ir cambiando según el último idioma que haya leído)
data.columns = ["Num of STAs", "Load", "Size(x)", "Size(y)", "Area(xy)", "Contention Window", 
                "Channel Width", "Packet Size", "Max RSSI", "Avg RSSI", "Min RSSI", "Avg Prob of Failure", 
                "Throughput", "Average Delay", "Total Airtime", "Proportional AirtimeS"]

In [7]:
data.head()

,Num of STAs,Load,Size(x),Size(y),Area(xy),Contention Window,Channel Width,Packet Size,Max RSSI,Avg RSSI,Min RSSI,Avg Prob of Failure,Throughput,Average Delay,Total Airtime,Proportional AirtimeS
0,40.0,60000000.0,22.0,39.0,858.0,63.0,80.0,4000.0,-42.928330,-63.163012,-74.965338,0.415189,7.208644e+06,1.229466e+07,1.084041,0.875490
1,35.0,52500000.0,20.0,33.0,660.0,31.0,40.0,10000.0,-47.815800,-63.298410,-72.847989,0.485311,1.545116e+07,1.275042e+07,1.111263,0.873785
2,16.0,12000000.0,34.0,14.0,476.0,255.0,40.0,4000.0,-46.138494,-60.076333,-70.044800,0.099413,6.743660e+06,2.251690e+06,0.880036,0.849701
3,37.0,18500000.0,35.0,7.0,245.0,31.0,80.0,10000.0,-42.708813,-60.141393,-72.029643,0.493704,1.675025e+07,1.211374e+07,1.126341,0.860103
4,18.0,4500000.0,36.0,35.0,1260.0,127.0,160.0,8000.0,-45.492991,-63.780783,-76.225550,0.011664,4.500000e+06,1.446000e-03,0.276770,0.275687

In [9]:
data.describe()

,Num of STAs,Load,Size(x),Size(y),Area(xy),Contention Window,Channel Width,Packet Size,Max RSSI,Avg RSSI,Min RSSI,Avg Prob of Failure,Throughput,Average Delay,Total Airtime,Proportional AirtimeS
count,100000.000000,1.000000e+05,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,1.000000e+05,1.000000e+05,100000.000000,100000.000000
mean,21.446170,2.140292e+07,20.562940,20.479640,421.270350,227.043920,75.106000,7997.580000,-45.911165,-57.577426,-66.467827,0.226676,9.716009e+06,4.688176e+06,0.780560,0.660724
std,11.554365,1.852042e+07,11.545206,11.540626,360.344349,323.350855,53.704279,2825.532513,5.400265,6.108548,8.057528,0.224848,4.958025e+06,7.875887e+06,0.360426,0.256756
min,2.000000,5.000000e+05,1.000000,1.000000,1.000000,3.000000,20.000000,4000.000000,-81.405165,-81.405165,-84.333834,0.000209,5.000000e+05,4.930000e-04,0.019793,0.019792
25%,11.000000,7.250000e+06,11.000000,11.000000,120.000000,15.000000,20.000000,6000.000000,-48.131476,-61.985000,-72.637078,0.036429,6.187692e+06,2.145750e-03,0.481082,0.473732
50%,21.000000,1.600000e+07,21.000000,20.000000,320.000000,63.000000,80.000000,8000.000000,-44.111064,-58.163205,-67.997587,0.126492,9.113764e+06,2.253349e+06,0.857473,0.781014
75%,31.000000,3.000000e+07,31.000000,30.000000,640.000000,255.000000,160.000000,10000.000000,-41.888821,-53.589525,-61.525848,0.400686,1.343290e+07,8.224326e+06,1.069432,0.866646
max,41.000000,8.200000e+07,40.000000,40.000000,1600.000000,1023.000000,160.000000,12000.000000,-40.863587,-40.865960,-40.865960,0.765422,2.262273e+07,5.330772e+08,1.449354,0.946776

In [10]:
print(data.isnull().sum())

Num of STAs              0
Load                     0
Size(x)                  0
Size(y)                  0
Area(xy)                 0
Contention Window        0
Channel Width            0
Packet Size              0
Max RSSI                 0
Avg RSSI                 0
Min RSSI                 0
Avg Prob of Failure      0
Throughput               0
Average Delay            0
Total Airtime            0
Proportional AirtimeS    0
dtype: int64

In [ ]:
#Preprocessing
categorical_cols = ["Num of STAs",  "Contention Window", "Channel Width", "Packet Size"]
numerical_cols = ["Load", "Size(x)", "Size(y)", "Area(xy)", "Max RSSI", "Avg RSSI", "Min RSSI", "Avg Prob of Failure", "Throughput", "Average Delay", "Total Airtime", "Proportional AirtimeS"]